from typing import Dict, NamedTuple, Set , Optional  #Edit these as needed.


class FP2Location:
    game = "Freedom Planet 2"

class FP2LocationData(NamedTuple):
    region: str
    item_id_offset: int
    location_group: Optional[str] = None


location_base_id = 9132022000 #this is apparently random, purely for AP. Not in the game itself.

location_table: Dict[str, FP2LocationData] = {
    #"Name of Check Location": FP2LocationData("Level", "Check type"),
    #Stage Clears and Chests:
    "Dragon Valley - Clear": FP2LocationData("Dragon Valley", 0, "Stage Clear"), 
    "Dragon Valley - Brave Stone": FP2LocationData("Dragon Valley", 1, "Chest"),
    "Dragon Valley - Vinyl": FP2LocationData("Dragon Valley", 2, "Chest"),
    "Shenlin Park - Clear": FP2LocationData("Shenlin Park", 3, "Stage Clear"),
    "Shenlin Park - Brave Stone": FP2LocationData("Shenlin Park", 4, "Chest"),
    "Shenlin Park - Vinyl": FP2LocationData("Shenlin Park", 5, "Chest"),
    "Avian Museum - Clear": FP2LocationData("Avian Museum", 6, "Stage Clear"),
    "Avian Museum - Brave Stone": FP2LocationData("Avian Museum", 7, "Chest"),
    "Avian Museum - Vinyl": FP2LocationData("Avian Museum", 8, "Chest"),
    "Airship Sigwada - Clear": FP2LocationData("Airship Sigwada", 9, "Stage Clear"),
    "Airship Sigwada - Brave Stone": FP2LocationData("Airship Sigwada", 10, "Chest"),
    "Airship Sigwada - Vinyl": FP2LocationData("Airship Sigwada", 11, "Chest"),
    "Phoenix Highway - Clear": FP2LocationData("Phoenix Highway", 12, "Stage Clear"),
    "Phoenix Highway - Brave Stone": FP2LocationData("Phoenix Highway", 13, "Chest"),
    "Phoenix Highway - Vinyl": FP2LocationData("Phoenix Highway", 14, "Chest"),
    "Zao Land - Clear": FP2LocationData("Zao Land", 15, "Stage Clear"),
    "Zao Land - Brave Stone": FP2LocationData("Zao Land", 16, "Chest"),
    "Zao Land - Vinyl": FP2LocationData("Zao Land", 17, "Chest"),
    "The Battlesphere - Clear": FP2LocationData("The Battlesphere 1st Pass", 18, "Stage Clear"),
    "Tiger Falls - Clear": FP2LocationData("Tiger Falls", 19, "Stage Clear"),
    "Tiger Falls - Brave Stone": FP2LocationData("Tiger Falls", 20, "Chest"),
    "Tiger Falls - Vinyl": FP2LocationData("Tiger Falls", 21, "Chest"),
    "Robot Graveyard - Clear": FP2LocationData("Robot Graveyard", 22, "Stage Clear"),
    "Robot Graveyard - Vinyl": FP2LocationData("Robot Graveyard", 23, "Chest"),
    "Shade Armory - Clear": FP2LocationData("Shade Armory", 24, "Stage Clear"),
    "Shade Armory - Vinyl": FP2LocationData("Shade Armory", 25, "Chest"),
    "Snowfields - Clear": FP2LocationData("Snowfields", 26, "Stage Clear"),
    "Globe Opera 1 - Clear": FP2LocationData("Globe Opera 1", 27, "Stage Clear"),
    "Globe Opera 1 - Vinyl": FP2LocationData("Globe Opera 1", 28, "Chest"),
    "Globe Opera 2 - Clear": FP2LocationData("Globe Opera 2", 29, "Stage Clear"),
    "Globe Opera 2 - Vinyl": FP2LocationData("Globe Opera 2", 30, "Chest"),
    "Auditorium - Clear": FP2LocationData("Auditorium", 31, "Stage Clear"),
    "Palace Courtyard - Clear": FP2LocationData("Palace Courtyard", 32, "Stage Clear"),
    "Tidal Gate - Clear": FP2LocationData("Tidal Gate", 33, "Stage Clear"),
    "Tidal Gate - Vinyl": FP2LocationData("Tidal Gate", 34, "Chest"),
    "Zulon Jungle - Clear": FP2LocationData("Zulon Jungle", 35, "Stage Clear"),
    "Zulon Jungle - Vinyl": FP2LocationData("Zulon Jungle", 36, "Chest"),
    "Nalao Lake - Clear": FP2LocationData("Nalao Lake", 37, "Stage Clear"),
    "Nalao Lake - Vinyl": FP2LocationData("Nalao Lake", 38, "Chest"),
    "Ancestral Forge - Clear": FP2LocationData("Ancestral Forge", 39, "Stage Clear"),
    #Should we see about looking into getting the rest of the chests in Ancestral Forge as checks?
    "Ancestral Forge - Vinyl": FP2LocationData("Ancestral Forge", 40, "Chest"),
    "Magma Starscape - Clear": FP2LocationData("Magma Starscape", 41, "Stage Clear"),
    "Magma Starscape - Vinyl": FP2LocationData("Magma Starscape", 42, "Chest"),
    "Diamond Point - Clear": FP2LocationData("Diamond Point", 43, "Stage Clear"),
    "Sky Bridge - Clear": FP2LocationData("Sky Bridge", 44, "Stage Clear"),
    "Sky Bridge - Vinyl": FP2LocationData("Sky Bridge", 45, "Chest"),
    "Lightning Tower - Clear": FP2LocationData("Lightning Tower", 46, "Stage Clear"),
    "Lightning Tower - Vinyl": FP2LocationData("Lightning Tower", 47, "Chest"),
    #Maybe we ought to consider splitting the next two stages from the Bakunawa stages.
    #They are technically separate from them in the base game, as far as I know.
    "Gravity Bubble - Clear": FP2LocationData("Gravity Bubble", 48, "Stage Clear"),
    "Gravity Bubble - Vinyl": FP2LocationData("Gravity Bubble", 49, "Chest"),
    "Bakunawa Chase - Clear": FP2LocationData("Bakunawa Chase", 50, "Stage Clear"),
    "Bakunawa Rush - Clear": FP2LocationData("Bakunawa Rush", 51, "Stage Clear"),
    "Bakunawa Rush - Vinyl": FP2LocationData("Bakunawa Rush", 52, "Chest"),
    "Refinery Room - Clear": FP2LocationData("Refinery Room", 53, "Stage Clear"),
    "Clockwork Arboretum - Clear": FP2LocationData("Clockwork Arboretum", 54, "Stage Clear"),
    "Clockwork Arboretum - Vinyl": FP2LocationData("Clockwork Arboretum", 55, "Chest"),
    "Inversion Dynamo - Clear": FP2LocationData("Inversion Dynamo", 56, "Stage Clear"),
    "Inversion Dynamo - Vinyl": FP2LocationData("Inversion Dynamo", 57, "Chest"),
    "Lunar Cannon - Clear": FP2LocationData("Lunar Cannon", 58, "Stage Clear"),
    "Lunar Cannon - Vinyl": FP2LocationData("Lunar Cannon", 59, "Chest"),
    "Merga - Clear": FP2LocationData("Merga", 60, "Stage Clear"),
    "Weapon's Core - Clear": FP2LocationData("Weapon's Core", 61, "Goal"),
    #Battlesphere Time Capsule Checks
    "The Battlesphere - Time Capsule 1": FP2LocationData("The Battlesphere", 62, "Time Capsule"),
    "The Battlesphere - Time Capsule 2": FP2LocationData("The Battlesphere", 63, "Time Capsule"),
    "The Battlesphere - Time Capsule 3": FP2LocationData("The Battlesphere", 64, "Time Capsule"),
    "The Battlesphere - Time Capsule 4": FP2LocationData("The Battlesphere", 65, "Time Capsule"),
    "The Battlesphere - Time Capsule 5": FP2LocationData("The Battlesphere", 66, "Time Capsule"),
    "The Battlesphere - Time Capsule 6": FP2LocationData("The Battlesphere", 67, "Time Capsule"),
    "The Battlesphere - Time Capsule 7": FP2LocationData("The Battlesphere", 68, "Time Capsule"),
    "The Battlesphere - Time Capsule 8": FP2LocationData("The Battlesphere", 69, "Time Capsule"),
    "The Battlesphere - Time Capsule 9": FP2LocationData("The Battlesphere", 70, "Time Capsule"),
    "The Battlesphere - Time Capsule 10": FP2LocationData("The Battlesphere", 71, "Time Capsule"),
    "The Battlesphere - Time Capsule 11": FP2LocationData("The Battlesphere", 72, "Time Capsule"),
    "The Battlesphere - Time Capsule 12": FP2LocationData("The Battlesphere", 73, "Time Capsule"),
    #Shop Items
    "Shop - Element Burst": FP2LocationData("Shop - Brave Stone", 74, location_group="Shop - Brave Stone"),
    "Shop - Crystals to Petals": FP2LocationData("Shop - Brave Stone", 75, location_group="Shop - Brave Stone"),
    "Shop - Petal Armor": FP2LocationData("Shop - Brave Stone", 76, location_group="Shop - Brave Stone"),
    "Shop - Extra Stock": FP2LocationData("Shop - Potion", 77, location_group="Shop - Potion"),
    "Shop - Strong Revivals": FP2LocationData("Shop - Potion", 78, location_group="Shop - Potion"),
    "Shop - Cheaper Stocks": FP2LocationData("Shop - Potion", 79, location_group="Shop - Potion"),
    "Shop - Healing Strike": FP2LocationData("Shop - Potion", 80, location_group="Shop - Potion"),
    "Shop - Attack Up": FP2LocationData("Shop - Potion", 81, location_group="Shop - Potion"),
    "Shop - Strong Shields": FP2LocationData("Shop - Potion", 82, location_group="Shop - Potion"),
    "Shop - Accelerator": FP2LocationData("Shop - Potion", 83, location_group="Shop - Potion"),
    "Shop - Super Feather": FP2LocationData("Shop - Potion", 84, location_group="Shop - Potion"),
    "Shop - Max Life Up": FP2LocationData("Shop - Brave Stone", 85, location_group="Shop - Brave Stone"),
    "Shop - One Hit KO": FP2LocationData("Shop - Brave Stone", 86, location_group="Shop - Brave Stone"),
    "Shop - Life Oscillation": FP2LocationData("Shop - Brave Stone", 87, location_group="Shop - Brave Stone"),
    "Shop - Items to Bombs": FP2LocationData("Shop - Brave Stone", 88, location_group="Shop - Brave Stone"),
    "Shop - Powerup Start": FP2LocationData("Shop - Brave Stone", 89, location_group="Shop - Brave Stone"),
    "Shop - Shadow Guard": FP2LocationData("Shop - Brave Stone", 90, location_group="Shop - Brave Stone"),
    "Shop - Payback Ring": FP2LocationData("Shop - Brave Stone", 91, location_group="Shop - Brave Stone"),
    "Shop - Wood Charm": FP2LocationData("Shop - Brave Stone", 92, location_group="Shop - Brave Stone"),
    "Shop - Earth Charm": FP2LocationData("Shop - Brave Stone", 93, location_group="Shop - Brave Stone"),
    "Shop - Water Charm": FP2LocationData("Shop - Brave Stone", 94, location_group="Shop - Brave Stone"),
    "Shop - Fire Charm": FP2LocationData("Shop - Brave Stone", 95, location_group="Shop - Brave Stone"),
    "Shop - Metal Charm": FP2LocationData("Shop - Brave Stone", 96, location_group="Shop - Brave Stone"),
    "Shop - Rainbow Charm": FP2LocationData("Shop - Brave Stone", 97, location_group="Shop - Brave Stone"),
    "Shop - Vinyl - Title Screen": FP2LocationData("Shop - Vinyl", 98, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Main Menu": FP2LocationData("Shop - Vinyl", 99, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Basic Tutorial": FP2LocationData("Shop - Vinyl", 100, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Globe Opera 2A": FP2LocationData("Shop - Vinyl", 101, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Weapon's Core": FP2LocationData("Shop - Vinyl", 102, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Robot A": FP2LocationData("Shop - Vinyl", 103, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Robot B": FP2LocationData("Shop - Vinyl", 104, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Aaa": FP2LocationData("Shop - Vinyl", 105, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Pheonix Highway": FP2LocationData("Shop - Vinyl", 106, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Zao Land": FP2LocationData("Shop - Vinyl", 107, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Arena": FP2LocationData("Shop - Vinyl", 108, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Captian Kalaw": FP2LocationData("Shop - Vinyl", 109, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Serpentine A": FP2LocationData("Shop - Vinyl", 110, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Serpentine B": FP2LocationData("Shop - Vinyl", 111, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Beast One/Two": FP2LocationData("Shop - Vinyl", 112, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Beast Three": FP2LocationData("Shop - Vinyl", 113, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - BFF2000": FP2LocationData("Shop - Vinyl", 114, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Diamond Point": FP2LocationData("Shop - Vinyl", 115, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Arboretum": FP2LocationData("Shop - Vinyl", 116, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Merga": FP2LocationData("Shop - Vinyl", 117, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Merga (Pinch)": FP2LocationData("Shop - Vinyl", 118, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Boss - Weapon's Core": FP2LocationData("Shop - Vinyl", 119, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Stage Clear": FP2LocationData("Shop - Vinyl", 120, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Results - Lilac": FP2LocationData("Shop - Vinyl", 121, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Results - Carol": FP2LocationData("Shop - Vinyl", 122, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Results - Milla": FP2LocationData("Shop - Vinyl", 123, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Results - Neera": FP2LocationData("Shop - Vinyl", 124, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Bonus Stage": FP2LocationData("Shop - Vinyl", 125, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Speed Gate": FP2LocationData("Shop - Vinyl", 126, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Shopping": FP2LocationData("Shop - Vinyl", 127, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Shang Tu": FP2LocationData("Shop - Vinyl", 128, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Shang Mu": FP2LocationData("Shop - Vinyl", 129, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Shuigang": FP2LocationData("Shop - Vinyl", 130, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Opera": FP2LocationData("Shop - Vinyl", 131, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Parusa": FP2LocationData("Shop - Vinyl", 132, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Floating Island": FP2LocationData("Shop - Vinyl", 133, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Volcano": FP2LocationData("Shop - Vinyl", 134, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Map - Bakunawa": FP2LocationData("Shop - Vinyl", 135, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Singing Water Temple": FP2LocationData("Shop - Vinyl", 136, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Royal Palace": FP2LocationData("Shop - Vinyl", 137, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Battlesphere Commercial": FP2LocationData("Shop - Vinyl", 138, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Battlesphere Lobby": FP2LocationData("Shop - Vinyl", 139, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Battlesphere Course": FP2LocationData("Shop - Vinyl", 140, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Captian Kalaw's Theme": FP2LocationData("Shop - Vinyl", 141, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Gallery": FP2LocationData("Shop - Vinyl", 142, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Shuigang": FP2LocationData("Shop - Vinyl", 143, location_group="Shop - Vinyl"),
    "Shop - Vinyl - City Hall": FP2LocationData("Shop - Vinyl", 144, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Adventure Square": FP2LocationData("Shop - Vinyl", 145, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Paradise Prime": FP2LocationData("Shop - Vinyl", 146, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Big Mood A": FP2LocationData("Shop - Vinyl", 147, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Big Mood B": FP2LocationData("Shop - Vinyl", 148, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Heroic": FP2LocationData("Shop - Vinyl", 149, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Preparation": FP2LocationData("Shop - Vinyl", 150, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Bakunawa": FP2LocationData("Shop - Vinyl", 151, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Lilac's Theme": FP2LocationData("Shop - Vinyl", 152, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Carol's Theme": FP2LocationData("Shop - Vinyl", 153, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Milla's Theme": FP2LocationData("Shop - Vinyl", 154, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Neera's Theme": FP2LocationData("Shop - Vinyl", 155, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Corazon's Theme": FP2LocationData("Shop - Vinyl", 156, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Serpentine's Theme": FP2LocationData("Shop - Vinyl", 157, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Merga's Theme": FP2LocationData("Shop - Vinyl", 158, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Audio Log A": FP2LocationData("Shop - Vinyl", 159, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Audio Log B": FP2LocationData("Shop - Vinyl", 160, location_group="Shop - Vinyl"),
    "Shop - Vinyl - Cutscene - Audio Log C": FP2LocationData("Shop - Vinyl", 161, location_group="Shop - Vinyl"),
}

location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[0]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)